### ISSUE TITLE
Tela de autenticação do sistema

### ISSUE THREAD

**Issue by lilialnas** [suelensalvino/Reciclatown#1]
Eu como usuário do sistema desejo ter uma tela de autenticação do sistema para garantir que o sistema está sendo utilizado pelas minhas credencias garantido meu acesso e segurança nos dados.

- [x] Realizar protótipo de interface e interação (cenários de exceção devem ser projetados como: esqueci a senha, usuário e senha incorretos, campos preenchidos incorretamente etc.)
- [x] Definir mecanismo de autenticação
- [x] Criação do backend (com validações de tamanho, obrigatoriedade de campos, fluxos alternativos de autenticação também)
- [x] Criação do frontend (máscara de preenchimento dos campos, validações de tamanho, obrigatoriedade de campos, fluxos alternativos de autenticação também)

**Comment by cleicykerolim** [comment]
![Protótipo - Reciclatown](https://user-images.githubusercontent.com/53884397/104976686-8e4cb100-59dc-11eb-9b95-a7589ed77541.jpg)

**Comment by desireefernandes** [comment]
![Esqueci a senha](https://user-images.githubusercontent.com/56517478/104985235-47b48200-59ef-11eb-9f81-c652702b43b8.jpg)
![Login](https://user-images.githubusercontent.com/56517478/104985240-48e5af00-59ef-11eb-878b-2e3d42fd173a.jpg)

**Comment by desireefernandes** [comment]
![Login](https://user-images.githubusercontent.com/56517478/104985320-6c105e80-59ef-11eb-8c96-45f9f1f6b13b.jpg)
![Esqueci a senha](https://user-images.githubusercontent.com/56517478/104985322-6e72b880-59ef-11eb-83d1-3b64e27506cd.jpg)
