### ISSUE TITLE
Criação de página inicial do sistema

### ISSUE THREAD

**Issue by lilialnas** [suelensalvino/Reciclatown#2]
Eu como usuário quero ter uma página inicial para poder acessar o sistema.

- [x] Criar protótipo de tela 
- [x] Incluir chamada para a tela de autenticação do sistema

**Comment by cleicykerolim** [comment]
![Protótipo - Reciclatown](https://user-images.githubusercontent.com/53884397/104977242-d28c8100-59dd-11eb-8e67-269cb7eb56f3.jpg)
