### ISSUE TITLE
Front-end do sistema

### ISSUE THREAD

**Issue by desireefernandes** [suelensalvino/Reciclatown#27]
* [x] Estudo de estilos de design e interface a serem implementados
* [x] Escolha da paleta
* [x] Definindo fluxo de interação do sistema
* [x] Estudo do framework Tailwindui
* [x] Testes com framework
* [x] Integração dos teste ao projeto
* [x] Criação dos protótipos
* [x] Criação do logotipo

**Comment by desireefernandes** [comment]
* [X] Escolha da paleta
![pl-of](https://user-images.githubusercontent.com/56517478/106166671-309e2e80-616b-11eb-9eb7-f8e360f768dd.png)

**Comment by desireefernandes** [comment]
* [x] Escolha da paleta

Código hex cores
#050259  |  #FFFFFF  |  #F27979
![PALETA-agr-vaaaaai](https://user-images.githubusercontent.com/56517478/106213485-94484c00-61ab-11eb-99e5-3d870f99c31d.png)

**Comment by desireefernandes** [comment]
* [ ] Criação dos protótipos 1/3

Tela de login
![login-pag](https://user-images.githubusercontent.com/56517478/106215484-d8d5e680-61af-11eb-9113-3165cf6259a6.jpg)

**Comment by cleicykerolim** [comment]
Protótipo da tela de apresentação que vem antes do cadastro e acesso

![Primeira página](https://user-images.githubusercontent.com/53884397/106225891-ca45fa00-61c4-11eb-85b3-720e97fdc198.jpg)

**Comment by cleicykerolim** [comment]
* [x] Criação dos protótipos
Protótipos e wireframes no figma: https://www.figma.com/file/wcTeeqHwX2k9Oxa3HYOptV/Untitled?node-id=0%3A1
Protótipo da página inicial

![Frame 5](https://user-images.githubusercontent.com/53884397/106226209-77b90d80-61c5-11eb-90f8-0e7ea2d073f0.jpg)

**Comment by desireefernandes** [comment]
Protótipo da página de login e redefinição de senha

![login-pag](https://user-images.githubusercontent.com/56517478/106274144-8d085900-6212-11eb-9342-dfb10c891cec.jpg)
![redefi](https://user-images.githubusercontent.com/56517478/106274146-8ed21c80-6212-11eb-8a6b-a196e4e3b687.jpg)

**Comment by desireefernandes** [comment]
* [x] Criação dos protótipos
![Dashboard](https://user-images.githubusercontent.com/56517478/110262016-06713500-7f91-11eb-9c13-6a45656dd97a.jpg)
![Modal - Dashboard](https://user-images.githubusercontent.com/56517478/110262023-0a04bc00-7f91-11eb-8d88-3a490908f83e.jpg)

**Comment by desireefernandes** [comment]
* [x] Criação do logotipo
![logo-a](https://user-images.githubusercontent.com/56517478/110399819-46015500-8055-11eb-9b7d-0b08b20f93d7.png)
