### ISSUE TITLE
Criação dos models e seeds [PARA CADA ENTIDADE]

### ISSUE THREAD

**Issue by lilialnas** [suelensalvino/Reciclatown#3]
Eu como desenvolvedor quero criar o model da entidade para salvar os dados banco de dados.

- [x]  Criar model

- [x]  Criar seed

**Comment by lilialnas** [comment]
Queridxs, essa issue vai ter que ser replicada a partir de quantas entidades vocês tiverem no projeto.
Meu mapa astral aqui ainda não consegue prever essa quantidade nem todas as redes neurais com Machine Learning também (ainda).

**Comment by ranierivalenca** [comment]
Pendências:
- [x] models devem seguir o modelo de CamelCase e começarem com letras maiúsculas
- [x] models devem ter as informações de relacionamento
- [x] seeds devem estar funcionando

**Comment by lilialnas** [comment]
Quebrem essa issue em várias :v:
