### ISSUE TITLE
Criar pagina de perfil do usuário

### ISSUE THREAD

**Issue by EverthonH** [suelensalvino/Reciclatown#54]
- [x] Criar rota para perfil do usuário.
- [x] Listar dados do usuário.
- [x] Editar dados do usuário.
- [x] Criar protótipo.
- [x] Front-end da página.
- [x] Troca de usuario para coletor.

**Comment by desireefernandes** [comment]
- [x] Criar protótipo.
![Perfil-pessoal](https://user-images.githubusercontent.com/56517478/110261884-aaa6ac00-7f90-11eb-9d4c-20eaeab96fb0.jpg)
