### ISSUE TITLE
Cadastrar produto a ser descartado

### ISSUE THREAD

**Issue by lilialnas** [suelensalvino/Reciclatown#8]
Como usuário descartante desejo cadastrar o(s) item(ns) para descarte para realizar o descarte de lixo eletrônico corretamente.

- [x]  Criar o protótipo de tela para termos noção que vai ser construído
- [x] Frontend da tela
- [x] Backend

OBS: Essa issue pode ser partidas em quantas a equipe achar necessário.

**Comment by lilialnas** [comment]
Incluir campo de descrição no cadastro do produto.

**Comment by desireefernandes** [comment]
- [x]  Criar o protótipo de tela para termos noção que vai ser construído
- [x] Frontend da tela
